#!/usr/bin/env python3
"""Stocktake — walk everything that exists and write down what is actually true.

Run it whenever you want to know where things stand:

    python3 "/Users/annikapeacock/Developer/claude code projects/stocktake/stocktake.py"

It writes /Users/annikapeacock/Desktop/Stocktake.md and prints anything that
wants attention. Read-only: it reads the filesystem and makes plain DNS and
HEAD requests, and changes nothing anywhere.

The point is that it re-derives itself. A hand-kept list of what you own goes
stale the first week and then quietly lies to you — which is exactly how two
Cloudflare accounts ended up holding different halves of the same project.
"""
import concurrent.futures
import datetime
import pathlib
import re
import subprocess

PROJECTS = pathlib.Path.home() / "Developer" / "claude code projects"
REPORT = pathlib.Path.home() / "Desktop" / "Stocktake.md"

# Cloudflare accounts, so the split is written down instead of rediscovered.
ACCOUNTS = {
    "fe332688b1b25b543f8429d7f08292a3": "Annika@pfau.haus — the working account: all zones, all Workers",
    "fc0c36ccbb118a0e5bba4562dd05f013": "skunkhaus — holds nothing in use; easy to land in by mistake",
}

# Why a repo has no GitHub remote. Anything absent from here and lacking a
# remote gets flagged rather than assumed to be deliberate.
LOCAL_ONLY = {
    "tel": "seizure telemetry — medical data, never push",
    "khwan": "ขวัญ interview vault — personal record, never push",
    "michael-go-court": "litigation material — never push",
    "rusty-chandelier": "paid client work",
    "stocktake": "this script",
}

DOMAINS = ["wichaa.net", "motdang.net", "poplucky.net", "defiant.to",
           "hakfarang.net", "offrampt.net", "hongdam.net", "nanobotco.github.io"]


def sh(args, cwd=None, timeout=25):
    try:
        return subprocess.run(args, cwd=cwd, capture_output=True,
                              text=True, timeout=timeout).stdout.strip()
    except Exception:
        return ""


def survey_domain(host):
    ns = [n.rstrip(".") for n in sh(["dig", "+short", "NS", host]).splitlines() if n.strip()]
    hdr = sh(["curl", "-sSI", "--max-time", "15", f"https://{host}/"])
    code = (re.search(r"^HTTP/\S+\s+(\d+)", hdr, re.M) or [None, ""])[1]
    server = (re.search(r"^server:\s*(.+)$", hdr, re.M | re.I) or [None, ""])[1].strip()
    proxied = bool(re.search(r"^cf-ray:", hdr, re.M | re.I))
    on_cf = any("cloudflare" in n for n in ns)

    if not code:
        state = "**dark** — bought, nothing served"
    elif proxied:
        state = "Cloudflare (proxied) → measurable"
    elif on_cf:
        state = "Cloudflare DNS, **grey cloud** — traffic bypasses Cloudflare"
    elif ns:
        state = "registrar DNS → origin direct"
    else:
        state = "—"
    return {"host": host, "http": code or "—", "server": server or "—",
            "ns": ns[0] if ns else "—", "state": state,
            "measurable": proxied}


def survey_repos():
    out = []
    for d in sorted(PROJECTS.iterdir()):
        if not (d / ".git").exists():
            continue
        branch = sh(["git", "branch", "--show-current"], cwd=d)
        remote = sh(["git", "remote", "get-url", "origin"], cwd=d)
        unpushed = sh(["git", "log", "--oneline", f"origin/{branch}..{branch}"], cwd=d) if remote and branch else ""
        cname = ""
        for c in (d / "docs" / "CNAME", d / "CNAME", d / "public" / "CNAME"):
            if c.exists():
                cname = c.read_text().strip()
                break
        workers = set()
        for w in d.rglob("wrangler.*"):
            if w.suffix not in (".toml", ".jsonc", ".json") or "node_modules" in str(w) or ".wrangler" in str(w):
                continue
            m = re.search(r'^\s*"?name"?\s*[:=]\s*"([^"]+)"', w.read_text(errors="ignore"), re.M)
            if m:
                workers.add(m.group(1))
        out.append({
            "name": d.name,
            "remote": remote.replace("https://github.com/", "").replace(".git", "") if remote else "",
            "last": sh(["git", "log", "-1", "--format=%cs"], cwd=d),
            "subject": sh(["git", "log", "-1", "--format=%s"], cwd=d)[:58],
            "dirty": len([l for l in sh(["git", "status", "--porcelain"], cwd=d).splitlines() if l]),
            "unpushed": len(unpushed.splitlines()) if unpushed else 0,
            "cname": cname, "workers": sorted(workers),
        })
    return out


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:
        doms = list(ex.map(survey_domain, DOMAINS))
    repos = survey_repos()
    today = datetime.date.today().isoformat()

    L = [f"# Stocktake — {today}", "",
         "Generated by `stocktake.py`. Re-run it rather than editing this file;",
         "anything hand-edited here is gone the next time it runs.", "",
         f"**{len(repos)} projects · {len(DOMAINS)} domains · "
         f"{sum(len(r['workers']) for r in repos)} Workers declared**", ""]

    L += ["## Domains", "",
          "| Domain | | Serving | State |", "| --- | --- | --- | --- |"]
    for d in doms:
        L.append(f"| **{d['host']}** | {d['http']} | {d['server']} | {d['state']} |")
    dark = [d["host"] for d in doms if d["http"] == "—"]
    grey = [d["host"] for d in doms if "grey" in d["state"]]
    L += ["", f"- Measurable by traffic-eye today: "
          f"{', '.join(d['host'] for d in doms if d['measurable']) or 'none'}"]
    if grey:
        L.append(f"- One toggle away (flip to proxied in Cloudflare): {', '.join(grey)}")
    if dark:
        L.append(f"- Bought but serving nothing: {', '.join(dark)}")
    L.append("")

    L += ["## Cloudflare accounts", ""]
    for aid, what in ACCOUNTS.items():
        L.append(f"- `{aid}` — {what}")
    L += ["", "Everything lives in the first one. Check the account picker before "
          "creating a token or enabling a product — they look identical otherwise.", ""]

    live_workers = sorted({w for r in repos for w in r["workers"]})
    L += ["## Workers", "", ", ".join(f"`{w}`" for w in live_workers), ""]

    L += ["## Needs attention", ""]
    flagged = False
    for r in sorted(repos, key=lambda x: -x["dirty"]):
        if r["dirty"] >= 5 or r["unpushed"]:
            bits = []
            if r["dirty"]:
                bits.append(f"{r['dirty']} uncommitted")
            if r["unpushed"]:
                bits.append(f"{r['unpushed']} unpushed")
            L.append(f"- **{r['name']}** — {', '.join(bits)} (last commit {r['last']})")
            flagged = True
    for r in repos:
        if not r["remote"] and r["name"] not in LOCAL_ONLY:
            L.append(f"- **{r['name']}** — no GitHub remote, and no recorded reason. "
                     f"Deliberate, or never pushed?")
            flagged = True
    if not flagged:
        L.append("Nothing outstanding.")
    L.append("")

    L += ["## Local only, on purpose", ""]
    for name, why in sorted(LOCAL_ONLY.items()):
        if any(r["name"] == name for r in repos):
            L.append(f"- **{name}** — {why}")
    L.append("")

    L += ["## Every project", "",
          "| Last | Project | GitHub | Serves | Workers |", "| --- | --- | --- | --- | --- |"]
    for r in sorted(repos, key=lambda x: x["last"], reverse=True):
        gh = r["remote"] or ("_local only_" if r["name"] in LOCAL_ONLY else "**no remote**")
        L.append(f"| {r['last']} | {r['name']} | {gh} | {r['cname'] or ''} | "
                 f"{', '.join(r['workers'])} |")
    L.append("")

    REPORT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {REPORT}")
    for line in L[L.index("## Needs attention") + 2:]:
        if not line.startswith("- "):
            break
        print(" ", line[2:].replace("**", ""))


main()
